module dbengine {
	exports it.cavallium.dbengine.database;
	exports it.cavallium.dbengine.rpc.current.data;
	exports it.cavallium.dbengine.database.remote;
	exports it.cavallium.dbengine.database.disk;
	exports it.cavallium.dbengine.rpc.current.data.nullables;
	exports it.cavallium.dbengine.database.serialization;
	exports it.cavallium.dbengine.client;
	exports it.cavallium.dbengine.client.query.current.data;
	exports it.cavallium.dbengine.database.collections;
	exports it.cavallium.dbengine.client.query;
	exports it.cavallium.dbengine.database.memory;
	opens it.cavallium.dbengine.database.remote;
	exports it.cavallium.dbengine.utils;
	exports it.cavallium.dbengine.database.disk.rocksdb;
	requires org.jetbrains.annotations;
	requires com.google.common;
	requires micrometer.core;
	requires rocksdbjni;
	requires org.apache.logging.log4j;
	requires static io.soabase.recordbuilder.core;
	requires it.unimi.dsi.fastutil;
	requires it.cavallium.datagen;
	requires java.logging;
	requires org.apache.commons.lang3;
	requires java.compiler;
	requires java.management;
	requires okio;
	requires moshi.records.reflect;
	requires moshi;
	requires static jdk.unsupported;
}